combine k8clster endpoints

diff --git a/.github/workflows/e2e-test.yml b/.github/workflows/e2e-test.yml
--- a/.github/workflows/e2e-test.yml
+++ b/.github/workflows/e2e-test.yml
@@ -17,17 +17,25 @@ jobs:
 
       - name: Monitor Pods in Kind
         run: |
-          timeout 90s kubectl get pods -w || exit 0
+          for i in {1..50}; do
+            STATUS=$(kubectl get pods --selector=job-name=e2e-inventory-http-tests -o jsonpath='{.items[0].status.phase}')
+            if [ "$STATUS" = "Succeeded" ]; then
+              echo "Test pod completed successfully."
+              exit 0
+            elif [ "$STATUS" = "Failed" ]; then
+              echo "Test pod failed."
+              exit 1
+            fi
+            sleep 1
+          done
+
+          echo "Timeout reached while waiting for the test pod to complete."
+          exit 1
 
       - name: View Test Pod Logs
         run: |
           TEST_POD=$(kubectl get pods --selector=job-name=e2e-inventory-http-tests -o jsonpath='{.items[0].metadata.name}')
-          kubectl logs $TEST_POD | tee test_logs.txt
-          
-          if grep -q -E "FAIL" test_logs.txt; then
-            echo "Test failed. Errors found in logs."
-            exit 1
-          fi
+          kubectl logs $TEST_POD
 
       - name: Inventory Down - Kind Cluster
         run: make inventory-down-kind
